# Generated by Django 6.0.7 on 2026-08-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('presentacion', models.CharField(blank=True, choices=[('entero', 'Entero'), ('colas', 'Colas')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo', 'talla'],
                'constraints': [models.UniqueConstraint(fields=('talla', 'tipo'), name='producto_talla_tipo_unico')],
            },
        ),
    ]
