# Generated by Django 6.0.7 on 2026-08-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('factura', models.CharField(blank=True, max_length=50)),
                ('pedimento', models.CharField(blank=True, max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='inventario.proveedor')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LoteGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('fecha_recibo', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_generales', to='inventario.camara')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_generales', to='inventario.entrada')),
            ],
            options={
                'ordering': ['-fecha_recibo'],
            },
        ),
        migrations.CreateModel(
            name='EntradaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_proveedor', models.CharField(max_length=50)),
                ('cajas', models.PositiveIntegerField()),
                ('peso_por_caja', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_kilos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_por_kilo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta_planeado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('camara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_detalle', to='inventario.camara')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventario.entrada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_detalle', to='inventario.producto')),
                ('lote_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_detalle', to='inventario.lotegeneral')),
            ],
            options={
                'ordering': ['-entrada__fecha'],
            },
        ),
    ]
