# Generated by Django 6.0.7 on 2026-08-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_entrada_lotegeneral_entradadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_de_salida', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField()),
                ('notas', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SalidaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajas', models.PositiveIntegerField()),
                ('total_kilos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura_proveedor', models.CharField(blank=True, max_length=50)),
                ('precio_x_kilo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_detalle', to='inventario.camara')),
                ('entrada_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_detalle', to='inventario.entradadetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_detalle', to='inventario.producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventario.salida')),
            ],
            options={
                'ordering': ['-salida__fecha'],
            },
        ),
    ]
