# Generated by Django 6.0.7 on 2026-08-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_salida_salidadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cajas', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('camara_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventario.camara')),
                ('camara_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.camara')),
                ('entrada_detalle_destino', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_camara_origen', to='inventario.entradadetalle')),
                ('entrada_detalle_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_como_lote_origen', to='inventario.entradadetalle')),
                ('salida', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_camara', to='inventario.salida')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
