# Generated by Django 6.0.7 on 2026-08-22 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_movimientocamara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocamara',
            name='salida',
        ),
        migrations.AddField(
            model_name='movimientocamara',
            name='salida_detalle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_camara', to='inventario.salidadetalle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientocamara',
            name='entrada_detalle_destino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_camara_como_destino', to='inventario.entradadetalle'),
        ),
        migrations.AlterField(
            model_name='movimientocamara',
            name='entrada_detalle_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_como_origen', to='inventario.entradadetalle'),
        ),
        migrations.AlterField(
            model_name='salidadetalle',
            name='camara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_detalle', to='inventario.camara'),
        ),
        migrations.AddConstraint(
            model_name='entradadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('lote_proveedor', ''), _negated=True), name='entradadetalle_lote_proveedor_no_vacio'),
        ),
    ]
