# Generated by Django 6.0.7 on 2026-08-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_movimientocamara_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='entradadetalle',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.entrada'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='inventario.cliente'),
        ),
        migrations.AlterField(
            model_name='salidadetalle',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.salida'),
        ),
    ]
