# Generated by Django 6.0.7 on 2026-09-01 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_camara_creado_por_cliente_creado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='es_internacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lotegeneral',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_generales_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidadetalle',
            name='notas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
