# Generated by Django 6.0.7 on 2026-09-01 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_entrada_es_internacional_lotegeneral_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadetalle',
            name='proveedor_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_de_origen', to='inventario.proveedor'),
        ),
    ]
