# Generated by Django 6.0.7 on 2026-09-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_backfill_proveedor_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadetalle',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
