# Generated by Django 6.0.7 on 2026-09-02 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_entradadetalle_fecha_caducidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicionEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=40)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('motivo', models.CharField(max_length=200)),
                ('editado_en', models.DateTimeField(auto_now_add=True)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ediciones_entrada', to=settings.AUTH_USER_MODEL)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ediciones', to='inventario.entrada')),
                ('entrada_detalle', models.ForeignKey(blank=True, help_text='Nulo cuando el campo editado es de la cabecera de la entrada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ediciones', to='inventario.entradadetalle')),
            ],
            options={
                'verbose_name': 'Edición de entrada',
                'verbose_name_plural': 'Ediciones de entradas',
                'ordering': ['-editado_en'],
            },
        ),
    ]
