# Generated by Django 6.0.7 on 2026-09-02 20:54

import django.db.models.deletion
from django.db import migrations, models


def rellenar_referencias(apps, schema_editor):
    """Los registros creados antes de estos campos siguen teniendo su FK viva,
    así que la referencia legible se puede reconstruir desde ella."""
    EdicionEntrada = apps.get_model('inventario', 'EdicionEntrada')

    for registro in EdicionEntrada.objects.select_related(
        'entrada__proveedor', 'entrada_detalle__producto'
    ):
        entrada = registro.entrada
        if entrada is None:
            continue
        proveedor = entrada.proveedor.nombre if entrada.proveedor_id else 'Sin proveedor'
        registro.entrada_referencia = (
            f"#{entrada.id} · {entrada.fecha} · {proveedor} · {entrada.factura or 'sin factura'}"
        )

        detalle = registro.entrada_detalle
        if detalle is not None:
            registro.linea_referencia = (
                f"{detalle.producto} · lote {detalle.lote_proveedor} · {detalle.cajas} cajas"
            )
        registro.save(update_fields=['entrada_referencia', 'linea_referencia'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_edicionentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicionentrada',
            name='entrada_referencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='edicionentrada',
            name='linea_referencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='edicionentrada',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ediciones', to='inventario.entrada'),
        ),
        migrations.AlterField(
            model_name='edicionentrada',
            name='entrada_detalle',
            field=models.ForeignKey(blank=True, help_text='Nulo cuando el campo editado es de la cabecera, o si la línea ya se borró.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ediciones', to='inventario.entradadetalle'),
        ),
        migrations.RunPython(rellenar_referencias, migrations.RunPython.noop),
    ]
