# Generated by Django 6.0.7 on 2026-09-03 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_edicionentrada_entrada_referencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='edicionentrada',
            index=models.Index(fields=['-editado_en'], name='edicionentrada_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['-fecha'], name='entrada_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='entradadetalle',
            index=models.Index(fields=['fecha_caducidad'], name='entdet_caducidad_idx'),
        ),
        migrations.AddIndex(
            model_name='lotegeneral',
            index=models.Index(fields=['-fecha_recibo'], name='lotegeneral_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocamara',
            index=models.Index(fields=['-fecha'], name='movcamara_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='salida',
            index=models.Index(fields=['-fecha'], name='salida_fecha_idx'),
        ),
    ]
