# Generated by Django 6.0.7 on 2026-09-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_edicionentrada_edicionentrada_fecha_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='notas',
            field=models.CharField(max_length=100),
        ),
    ]
