# Generated by Django 6.0.7 on 2026-09-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alter_salida_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadetalle',
            name='peso_por_caja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
