# Generated by Django 6.0.7 on 2026-09-24 17:39

from decimal import ROUND_HALF_UP, Decimal

import django.core.validators
from django.db import migrations, models


def corregir_peso_por_caja(apps, schema_editor):
    """
    La 0017 volvió obligatorio peso_por_caja rellenando con 0 los lotes que lo
    tenían vacío, y cajas_disponibles divide entre ese valor. Se deriva de lo
    que sí se capturó: total_kilos / cajas (o el lote entero como una sola caja
    si no tiene cajas).
    """
    EntradaDetalle = apps.get_model('inventario', 'EntradaDetalle')
    for lote in EntradaDetalle.objects.filter(peso_por_caja__lte=0).only('id', 'cajas', 'total_kilos'):
        peso = lote.total_kilos / lote.cajas if lote.cajas else lote.total_kilos
        lote.peso_por_caja = max(
            Decimal(peso).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP),
            Decimal('0.01'),
        )
        lote.save(update_fields=['peso_por_caja'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_alter_entradadetalle_peso_por_caja'),
    ]

    operations = [
        migrations.RunPython(corregir_peso_por_caja, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='entradadetalle',
            name='peso_por_caja',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
