# Generated by Django 6.0.7 on 2026-09-29 17:32

import django.db.models.deletion
from django.db import migrations, models

EMPRESA_POR_DEFECTO = 'IMPORTADORA'
EMPRESAS = [EMPRESA_POR_DEFECTO, 'MARISCOS SELECTOS']


def crear_empresas_y_asignar(apps, schema_editor):
    """
    Da de alta las dos empresas del grupo y asigna IMPORTADORA a las entradas
    que ya existían: hasta este cambio todo lo capturado era de Importadora.
    get_or_create por nombre: si ya existen (p. ej. dadas de alta a mano en el
    catálogo), no se duplican.
    """
    Empresa = apps.get_model('inventario', 'Empresa')
    Entrada = apps.get_model('inventario', 'Entrada')
    for nombre in EMPRESAS:
        Empresa.objects.get_or_create(nombre=nombre)
    importadora = Empresa.objects.get(nombre=EMPRESA_POR_DEFECTO)
    Entrada.objects.filter(empresa__isnull=True).update(empresa=importadora)


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_corregir_peso_por_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='inventario.empresa'),
        ),
        migrations.RunPython(crear_empresas_y_asignar, migrations.RunPython.noop),
    ]
