# Generated by Django 6.0.7 on 2026-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_areas_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioarea',
            name='solo_lectura',
            field=models.BooleanField(default=False),
        ),
    ]
