# Generated by Django 6.0.7 on 2026-07-31 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=5)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(unique=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('responsable_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_aperturados', to=settings.AUTH_USER_MODEL)),
                ('responsable_cierre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_cerrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], max_length=1)),
                ('autorizo', models.CharField(max_length=150)),
                ('beneficiario', models.CharField(max_length=200)),
                ('concepto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('corte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='treasury.cortecaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_tesoreria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoDivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=6, help_text='Tipo de cambio aplicado al momento del movimiento.', max_digits=18, null=True)),
                ('equivalente_mxn', models.DecimalField(blank=True, decimal_places=2, help_text='Valor histórico en pesos.', max_digits=18, null=True)),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.divisa')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisas', to='treasury.movimientotesoreria')),
            ],
            options={
                'unique_together': {('movimiento', 'divisa')},
            },
        ),
        migrations.CreateModel(
            name='SaldoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_final', models.DecimalField(db_column='saldo', decimal_places=2, default=0, max_digits=18)),
                ('saldo_fisico', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='treasury.cortecaja')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.divisa')),
            ],
            options={
                'unique_together': {('corte', 'divisa')},
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_mxn', models.DecimalField(decimal_places=6, max_digits=18)),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_cambio', to='treasury.divisa')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'divisa')},
            },
        ),
    ]
