# Generated by Django 6.0.7 on 2026-07-31 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_alter_cortecaja_responsable_cierre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientotesoreria',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientotesoreria',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientotesoreria',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientotesoreria',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimientotesoreria',
            name='usuario_cancelacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
    ]
