# Generated by Django 6.0.7 on 2026-07-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_movimientotesoreria_cancelado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientotesoreria',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
