# Generated by Django 6.0.7 on 2026-08-01 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_fix_fecha_datetimefield_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_termino', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='treasury.cortecaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hora_termino'],
            },
        ),
        migrations.CreateModel(
            name='ArqueoDivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=18)),
                ('resultado_esperado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_contado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisas', to='treasury.arqueocaja')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.divisa')),
            ],
            options={
                'unique_together': {('arqueo', 'divisa')},
            },
        ),
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tipo', models.CharField(choices=[('B', 'Billete'), ('M', 'Moneda')], max_length=1)),
                ('activa', models.BooleanField(default=True)),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='treasury.divisa')),
            ],
            options={
                'ordering': ['divisa__codigo', '-valor'],
                'unique_together': {('divisa', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='ArqueoConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piezas', models.PositiveIntegerField(default=0)),
                ('arqueo_divisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='treasury.arqueodivisa')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.denominacion')),
            ],
            options={
                'unique_together': {('arqueo_divisa', 'denominacion')},
            },
        ),
    ]
