# Generated by Django 6.0.7 on 2026-08-01 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0006_arqueocaja_arqueodivisa_denominacion_arqueoconteo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='denominacion',
            unique_together={('divisa', 'valor', 'tipo')},
        ),
    ]
