# Generated by Django 6.0.7 on 2026-08-01 14:27

import django.core.validators
import django.db.models.deletion
import treasury.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0007_alter_denominacion_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=treasury.models.ruta_adjunto_movimiento, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'xlsx', 'pdf'], message='No se permite el tipo de archivo “%(extension)s”. Solo se aceptan: %(allowed_extensions)s.')])),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_contenido', models.CharField(blank=True, max_length=100)),
                ('tamano', models.PositiveIntegerField()),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='treasury.movimientotesoreria')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subido_en'],
            },
        ),
    ]
