# Generated by Django 6.0.7 on 2026-08-04 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0009_puesto_rancho_nominasemanal_empleado_nominadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_cuenta',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='empleado',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='treasury.banco'),
        ),
    ]
