# Generated by Django 6.0.7 on 2026-08-07 16:39

from django.db import migrations, models


def sembrar_configuracion_folio(apps, schema_editor):
    ConfiguracionFolio = apps.get_model('treasury', 'ConfiguracionFolio')
    for tipo in ('I', 'E'):
        ConfiguracionFolio.objects.get_or_create(tipo=tipo, defaults={'siguiente_folio': 1})


def eliminar_configuracion_folio(apps, schema_editor):
    ConfiguracionFolio = apps.get_model('treasury', 'ConfiguracionFolio')
    ConfiguracionFolio.objects.filter(tipo__in=('I', 'E')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0010_banco_remove_empleado_cuenta_empleado_nombre_cuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], max_length=1, unique=True)),
                ('siguiente_folio', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Configuración de folio',
                'verbose_name_plural': 'Configuración de folios',
            },
        ),
        migrations.RunPython(sembrar_configuracion_folio, eliminar_configuracion_folio),
    ]
