# Generated by Django 6.0.7 on 2026-08-07 18:08

import django.db.models.deletion
from django.db import migrations, models


def dejar_un_arqueo_por_corte(apps, schema_editor):
    """Antes del bug arreglado, un corte podía terminar con varios arqueos.
    Nos quedamos con el más reciente (por hora_termino) y borramos el resto,
    para poder aplicar la restricción unique=True sin que falle la migración."""
    ArqueoCaja = apps.get_model('treasury', 'ArqueoCaja')
    cortes_con_duplicados = (
        ArqueoCaja.objects.values('corte')
        .order_by()
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .values_list('corte', flat=True)
    )
    for corte_id in cortes_con_duplicados:
        arqueos = ArqueoCaja.objects.filter(corte_id=corte_id).order_by('-hora_termino')
        for arqueo in arqueos[1:]:
            arqueo.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0011_configuracionfolio'),
    ]

    operations = [
        migrations.RunPython(dejar_un_arqueo_por_corte, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='arqueocaja',
            name='corte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='treasury.cortecaja', unique=True),
        ),
    ]
