# Generated by Django 6.0.7 on 2026-09-03 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0012_alter_arqueocaja_corte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimientotesoreria',
            index=models.Index(fields=['-fecha', '-creado'], name='movtesoreria_fecha_idx'),
        ),
    ]
