# Generated by Django 6.0.7 on 2026-10-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0014_caja_por_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aperturaperiodo',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='aperturaperiodo',
            name='editado_por',
        ),
        migrations.DeleteModel(
            name='AperturaDivisa',
        ),
        migrations.DeleteModel(
            name='AperturaPeriodo',
        ),
    ]
