# Generated by Django 6.0.7 on 2026-10-02 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0015_quitar_aperturas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('editado_en', models.DateTimeField(auto_now=True)),
                ('divisa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='saldo_inicial', to='treasury.divisa')),
                ('editado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_iniciales_editados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
